home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index),
    path('homepage', views.index),
    path('develop_log', views.get_develop_log),
    path('login',views.get_login_page),
    path('signup', views.get_signup_page),

    path('save_data', views.post_user_info),
    path('authen', views.post_user_login),
    path('logout', views.user_logout),

    path('board', views.get_board_list),
    path('write-post', views.get_write_post),
    path('posting', views.post_document),
    path('postview', views.postview, name='view_post'),

    path('comment/new', views.save_new_comment, name='new_comment'),
    path('comment/delete', views.delete_comment)
]

shyunku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin-authentification/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
]

home/models.py
from django.db import models
from django_summernote import models as summer_model
from django_summernote import fields as summer_fields

from django.urls import reverse



class User_Info(models.Model):
    user_id = models.CharField(max_length=20)
    user_nickname = models.CharField(max_length=25)
    user_pw = models.CharField(max_length=15)

    def __str__(self):
        return self.user_id


class Variables(models.Model):
    doc_index_recent = models.IntegerField(default=0)
    comment_index_recent = models.IntegerField(default=0)

    visits = models.IntegerField(default=0)
    visits_free = models.IntegerField(default=0)
    visits_rout = models.IntegerField(default=0)
    visits_lol = models.IntegerField(default=0)
    visits_dl = models.IntegerField(default=0)
    visits_web = models.IntegerField(default=0)
    visits_java = models.IntegerField(default=0)
    visits_window = models.IntegerField(default=0)
    visits_indiv = models.IntegerField(default=0)

    def __str__(self):
        return "Variables"


class Documents_Info(models.Model):
    def get_absolute_url(self):
        return reverse(
            'home:view_post', args={
                'pindex':self.doc_index,
                'classify':self.classify
            }
        )

    classify = models.CharField(max_length=20)
    doc_index = models.CharField(default="00001", max_length=15)
    doc_title = models.CharField(max_length=20)
    doc_writer = models.CharField(default="shyunku", max_length=20)
    doc_content = models.TextField(default="")
    doc_time = models.DateTimeField(auto_now_add=True, blank=True)
    doc_view_cnt = models.IntegerField(default=0)

    def __str__(self):
        return self.classify + "-" + self.doc_index + "-" + self.doc_writer + "-" + self.doc_title


class Comment(models.Model):
    comment_time = models.DateTimeField(auto_now_add=True, blank=True)
    comment_content = models.TextField(default="")
    comment_writer = models.ForeignKey(User_Info, null=True, on_delete=models.CASCADE)
    comment_post = models.ForeignKey(Documents_Info, null=True, on_delete=models.CASCADE, related_name="commented")
    comment_id = models.CharField(default="000001", max_length=15)

    def __str__(self):
        return self.comment_post.__str__() + "-" + self.comment_writer.user_nickname


class SummerNote(summer_model.Attachment):
    summer_field = summer_fields.SummernoteTextField(default='')

home/forms.py
from django import forms
from django_summernote import fields as summer_fields
from .models import SummerNote


class UserForm(forms.Form):
    user_id = forms.CharField(label='id', max_length=15)
    user_nickname = forms.CharField(label='nickname', max_length=20)
    user_pw = forms.CharField(label='pw', max_length=15)


class PostForm(forms.ModelForm):
    fields = summer_fields.SummernoteTextFormField(error_messages={'required': (u'데이터를 입력해주세요'), })

    class Meta:
        model = SummerNote
        fields = ('fields',)

home/views.py
from django.conf import settings
from home.models import User_Info, Variables, Documents_Info, Comment
from home.forms import PostForm
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from home.custom import *
from django.http import HttpResponseForbidden


context_default = {
    'version': settings.SITE_VER,
    'css_version': settings.CSS_VER,
    'superuser_id': settings.SUPERUSER_ID,
    'user_info_condition': settings.USER_INFO_CONDITION,
    'process_rate': settings.PROCESS_RATE,
}

document_context = {
    'document_info' : Documents_Info.objects.all(),
}


def update_context():
    global document_context, context_default
    document_context = {
        'document_info': Documents_Info.objects.all(),
    }
    datas = Variables.objects.all()
    if len(datas) == 0:
        obj = Variables(
            visits= 0,
            doc_index_recent= 0,
            visits_free=0,
            visits_rout=0,
            visits_lol=0,
            visits_dl=0,
            visits_web=0,
            visits_java=0,
            visits_window=0,
            visits_indiv=0
        )
        obj.save()
    context_default = {
        'version'            : settings.SITE_VER,
        'css_version'        : settings.CSS_VER,
        'superuser_id'       : settings.SUPERUSER_ID,
        'user_info_condition': settings.USER_INFO_CONDITION,
        'variables'          : Variables.objects.all().first(),
        'process_rate'       : settings.PROCESS_RATE,
    }


def index(request):
    save_count = 0
    for visit_counter in Variables.objects.filter().all():
        save_count = visit_counter.visits+1
        break

    Variables.objects.filter().all().update(visits=save_count)

    context2 = {
        'superuser_id': settings.SUPERUSER_ID,
    }
    update_context()
    return render(request, 'major/homepage.html', merge_dicts(context_default, context2))


def get_develop_log(request):
    update_context()

    return render(request, 'major/development_log.html', context_default)


def get_login_page(request):
    update_context()
    User_Infos = User_Info.objects.all()

    prev = request.GET.get('call')
    login_context = {
        'user_information': User_Infos,
        'previous_call' : prev,
    }
    return render(request, 'major/login_page.html', merge_dicts(context_default, login_context))


def get_signup_page(request):
    update_context()
    User_Infos = User_Info.objects.all()
    login_context = {
        'user_information': User_Infos,
    }
    return render(request, 'major/signup.html', merge_dicts(context_default, login_context))


def post_user_info(request):
    obj = User_Info(
        user_id=request.POST.get('user-id'),
        user_nickname=request.POST.get('user-nickname'),
        user_pw=request.POST.get('user-pw')
    )
    obj.save()
    return redirect('/login')


def post_user_login(request):
    for user in User_Info.objects.filter().all():
        if user.user_id == request.POST.get('user-id'):
            request.session['username'] = user.user_nickname
            request.session['userid'] = user.user_id
            break

    previous = request.GET.get('call')

    if previous == None:
        return redirect('/homepage')
    return redirect('/board?name=' + previous)


def user_logout(request):
    try:
        del request.session['username']
        del request.session['userid']
    except:
        pass
    return redirect('/homepage')


def get_board_list(request):
    update_context()

    classification = request.GET.get('name')

    visit_num = update_visits(classification)

    board_name = switch_urlname_to_board_name(classification)

    post_all_list = Documents_Info.objects.filter(classify=classification).order_by('doc_index').reverse()
    paginator = Paginator(post_all_list, settings.PAGE_MAX_DETAILS)

    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    ranger = range(1,settings.PAGE_MAX_CHAPTER+1)

    if page != None :
        pagei = int(page)
        page_page = (int)((pagei-1)/settings.PAGE_MAX_CHAPTER)
        ranger = range(
            page_page * settings.PAGE_MAX_CHAPTER + 1,
            (page_page+1) * settings.PAGE_MAX_CHAPTER + 1,
                            )

    page_viewed_total = 0
    posts_num = len(post_all_list)


    for post_data in post_all_list:
        page_viewed_total += post_data.doc_view_cnt

    addition = {
        'posts' : posts,
        'max_page': settings.PAGE_MAX_CHAPTER,
        'page_range': ranger,
        'board_name' : board_name,
        'classification' : classification,
        'visits': visit_num,
        'post_num': posts_num,
        'page_viewed_total': page_viewed_total,
    }
    merged = merge_dicts(context_default, document_context)
    return render(request, 'major/post_list.html', merge_dicts(merged, addition))



# WRITE PAGES


def get_write_post(request):
    update_context()
    pform = PostForm()

    if 'userid' not in request.session:
        return render(request, 'major/forbidden.html', context_default)

    classification = request.GET.get('board')
    board_rename = switch_urlname_to_board_name_trick(classification)
    addition = {
        'form' : pform,
        'board_name' : board_rename,
        'classification' : classification
    }
    merged = merge_dicts(context_default, document_context)
    return render(request, 'major/new_post.html', merge_dicts(merged, addition))



# Posting PAGES


def post_document(request):
    recent_index = Variables.objects.all().first().doc_index_recent + 1
    Variables.objects.all().update(doc_index_recent=recent_index)

    classification = request.GET.get('board')

    new_doc = Documents_Info(
        classify= classification,
        doc_index='{:05d}'.format(recent_index),
        doc_title=request.POST.get('doc-title'),
        doc_writer=request.session['username'],
        doc_content=request.POST.get('fields'),
        doc_view_cnt=0
    )

    new_doc.save()

    url_trick = request.GET.get('board')

    return redirect('/board?name='+url_trick)


# Post View


def postview(request):
    update_context()

    classification = request.GET.get('classify')
    board_name = switch_urlname_to_board_name_trick(classification)

    post_index = request.GET.get('pindex')
    datas = Documents_Info.objects.filter(doc_index=post_index)
    Documents_Info.objects.filter(doc_index=post_index).update(doc_view_cnt= datas.first().doc_view_cnt+1)

    post = Documents_Info.objects.filter(doc_index=post_index).first()


    addition = {
        'doc_data' : datas.first(),
        'board_name' : board_name,
        'post': post,
    }

    merged = merge_dicts(context_default, document_context)
    return render(request, 'major/show_post.html', merge_dicts(merged, addition))


def save_new_comment(request):
    if request.method == 'POST':

        recent_index = Variables.objects.all().first().comment_index_recent + 1
        Variables.objects.all().update(comment_index_recent=recent_index)

        post = Documents_Info.objects.filter(doc_index=request.POST['post_id']).first()
        user = User_Info.objects.filter(user_id=request.session['userid']).first()
        Comment.objects.create(
            comment_content=request.POST['comment_contents'],
            comment_writer=user,
            comment_post=post,
            comment_id='{:06d}'.format(recent_index),
        )
        return redirect('/postview?pindex='+post.doc_index+'&classify='+post.classify)


def delete_comment(request):
    comment_id = request.GET.get('comment_id')
    comment_obj = Comment.objects.filter(comment_id=comment_id).first()
    post = comment_obj.comment_post
    comment_obj.delete()

    return redirect('/postview?pindex='+post.doc_index+'&classify='+post.classify)

home/templates/major/development_log.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="../../static/main_style.css?ver={{ css_version }}">
        <link href="https://fonts.googleapis.com/css?family=Do+Hyeon|Noto+Serif+KR|Noto+Sans+KR&display=swap&subset=korean" rel="stylesheet">
        <title>션쿠의 잊혀진 블로그</title>
    </head>
    <body>
        <!-- 아래까지 공통 부분 -->
        <div class="background-content">
            <div class="logo">
                <a href="../homepage">
                    {% load static %}
                    <img src="{% static "logo.png" %}">
                </a>
            </div>
            <div class="vertical-center">
                <div class="wrapper">
                    {% if request.session.username == None %}
                        <li><a href="../signup">회원가입</a></li>
                        <li><a href="../login">로그인</a></li>
                    {% else %}
                        {% if request.session.userid ==  superuser_id %}
                            블로그 관리자 님, 환영합니다!
                        {% else %}
                            {{ request.session.username }} 님, 환영합니다!
                        {% endif %}
                        <li><a href="../logout">로그아웃</a></li>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="menu">
            <li><a href="../board?name=free">자유게시판</a></li>
            <li><a href="../board?name=routine">일상</a></li>
            <li><a href="../board?name=league-of-legends">리그오브레전드</a></li>
            <li><a href="../board?name=deep-learning">Deep-Learning</a></li>
            <li><a href="../board?name=web">WEB</a></li>
            <li><a href="../board?name=java">JAVA</a></li>
            <li><a href="../board?name=window-issues">Window Issues</a></li>
            <li><a href="../board?name=individual">개인</a></li>
            <li><a href="../develop_log">사이트 개발로그</a></li>
        </div>
        <!-- 위까지 공통 부분 -->
        <div class="body-content">
            <div class="wrap-content">
                <div class="title-content">
                    <h1>션쿠의 블로그 개발 현황 및 로그</h1>
                </div>
                <div class="semi-title">
                VERSION : {{ version }}<br>Last Update : 2019-05-28 AM 5:51
                </div>
                <div class="main-content">
                    <div class="done">
                        <br><h4>version 1.0.0</h4>
                        <div class="indented">
                            - 서버 인스턴스 복구<br>
                            - 유지 보수 중단<br>
                        </div>
                        <br><h4>version 0.7.X</h4>
                        <div class="indented">
                            - 서버 호스팅 구현<br>
                            - 이제 블로그 관리자가 아닌 외부인이 자유게시판이 아닌 게시판에 게시글 달 수 없음<br>
                        </div>
                        <br><h4>version 0.6.X</h4>
                        <div class="indented">
                            - 댓글 삭제 안되는 오류 수정<br>
                            - 날짜/시간 표현 수정<br>
                            - 댓글 삭제 기능 추가<br>
                            - 이제 댓글 등록 시 내용 없으면 form action 리턴하지 않음<br>
                            - 닉네임 중복 확인 후 닉네임 필드 값 초기화<br>
                            - 이제 자신의 댓글만 삭제할 수 있음, 블로그 관리자는 항상 삭제 가능<br>
                            - 갈 수 없는 페이지에 접근시 forbidden 처리<br>
                            - 코드 부분 최적화<br>
                            - show post 시 게시자 이름 및 포스팅 시간, 조회수 표시<br>
                            - ID 중복 확인 후 ID 필드 값 초기화<br>
                            - POST request 처리 후 URL 문제 해결<br>
                            - 댓글에 닉네임이 아닌 ID가 표시되는 오류 수정<br>
                            - 댓글 기능 구현<br>
                            - 댓글 등록 시 스크롤 위치로 리턴, 애니메이션 추가<br>
                            - 회원가입 시 ID 중복 확인 구현<br>
                        </div>
                        <br><h4>version 0.5.X</h4>
                        <div class="indented">
                            - 게시판 페이지 탭 구조 변경<br>
                            - 게시판 페이지 탭 안뜨는 오류 수정<br>
                            - 블로그관리자만 개인 게시판을 관리할 수 있도록 수정<br>
                            - 로그인 탭의 정보 기억하기 삭제<br>
                            - 게시글에 조회수 및 Path 표시 구현<br>
                            - 내용이 증가함에 따라 div height이 증가하지 않는 오류 수정<br>
                        </div>
                        <br><h4>version 0.4.X</h4>
                        <div class="indented">
                            - 비로그인 상태로 게시판에서 포스트 시도 시 로그인으로 전송 및 콜백 구현<br>
                            - 버그 수정<br>
                            - 포스트 글쓰기 페이지 정규화<br>
                            - 게시판 마다 정보 업데이트되게 수정<br>
                            - 거의 대부분의 페이지 구현 완료<br>
                        </div>
                        <br><h4>version 0.3.X</h4>
                        <div class="indented">
                            - 페이지 탭 구현<br>
                            - 조회수 실시간으로 안되는 오류 수정<br>
                            - 템플릿 업데이트가 안되는 오류 수정<br>
                            - 게시글 작성 구현<br>
                            - summernote form post 데이터 저장<br>
                            - summernote form post 데이터 표현<br>
                        </div>
                        <br><h4>version 0.2.X</h4>
                        <div class="indented">
                            - 로그아웃할 때 유저 ID 세션 남아있는 오류 수정<br>
                            - 게시글 작성 폼 구현<br>
                            - 유저 정보 조건 관리 최적화<br>
                            - 게시글 리스트 페이지 템플릿 85% 구현<br>
                            - 페이지 조회수 측정 구현<br>
                            - 블로그 superuser(관리자) 인식 구현<br>
                            - 로그인/로그아웃 세션 구현<br>
                        </div>
                        <br><h4>under version 0.2.0</h4>
                        <div class="indented">
                            - 회원가입 창 구현<br>
                            - 회원가입 DB 연동 구현<br>
                            - 로그인 DB 연동 구현<br>
                            - 로그인 페이지 템플릿 90% 구현<br>
                            - 회원가입 탭 추가<br>
                            - 로그인 페이지 구현<br>
                            - 로그인 탭 구현<br>
                            - version string Global Variable로 구현하여 HTML과 연동 완료<br>
                            - 메뉴 탭 다량 추가<br>
                            - indented div class 구현<br>
                            - 사이트 개발로그 페이지 개발 시작<br>
                            - 사이트 개발로그 페이지 URL 작업 완료<br>
                            - 홈페이지 - logo URL 작업 완료<br>
                            - 사이트 개발로그 페이지 기본 템플릿 완성<br>
                        </div>
                    </div>
                    <div class="to-do">
                        <br><h4>To-Do Preferred</h4>
                        <div class="indented">
                            - 게시글 수정 및 삭제 기능 추가<br>
                            - 게시글 검색 기능 추가<br>
                        </div>
                        <br><h4>To-Do List</h4>
                        <div class="indented">
                            - 홈페이지 글 수정 기능 추가<br>
                            - 댓글 navigator 완성<br>
                            - 댓글 답글 기능 추가 (최상위 계층 댓글 대상)<br>
                            - 포스팅 시 사진 저장 추가<br>
                            - 게시글 포스팅 시 내용 없으면 오류 리턴<br>
                        </div>
                        <br><h4>To-Do Low-Preference</h4>
                        <div class="indented">
                            - 댓글 등록 시 그 자리에서 바로 애니메이션으로 추가<br>
                            - 디스플레이 우측 Go Top 추가 (보류)<br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

home/templates/major/show_post.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="../../static/main_style.css?ver={{ css_version }}">
        <link rel="stylesheet" type="text/css" href="../../static/document_post.css?ver={{ css_version }}">
        <link rel="stylesheet" type="text/css" href="../../static/page_navigator.css?ver={{ css_version }}">
        <link rel="stylesheet" type="text/css" href="../../static/comments.css?ver={{ css_version }}">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Do+Hyeon|Noto+Serif+KR|Noto+Sans+KR&display=swap&subset=korean" rel="stylesheet">
        <title>션쿠의 잊혀진 블로그</title>
    </head>
    <body>
        <script>
            $(document).ready(function(){
                let scroll_pos = localStorage.getItem("scroll-position");
                if(scroll_pos) {
                    $('body,html').animate({
                        scrollTop: scroll_pos
                    }, 600);
                    localStorage.removeItem("scroll-position");
                }
            });
        </script>
        <!-- 아래까지 공통 부분 -->
        <div class="background-content">
            <div class="logo">
                <a href="../homepage">
                    {% load static %}
                    <img src="{% static "logo.png" %}">
                </a>
            </div>
            <div class="vertical-center">
                <div class="wrapper">
                    {% if request.session.username == None %}
                        <li><a href="../signup">회원가입</a></li>
                        <li><a href="../login">로그인</a></li>
                    {% else %}
                        {% if request.session.userid ==  superuser_id %}
                            블로그 관리자 님, 환영합니다!
                        {% else %}
                            {{ request.session.username }} 님, 환영합니다!
                        {% endif %}
                        <li><a href="../logout">로그아웃</a></li>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="menu">
            <li><a href="../board?name=free">자유게시판</a></li>
            <li><a href="../board?name=routine">일상</a></li>
            <li><a href="../board?name=league-of-legends">리그오브레전드</a></li>
            <li><a href="../board?name=deep-learning">Deep-Learning</a></li>
            <li><a href="../board?name=web">WEB</a></li>
            <li><a href="../board?name=java">JAVA</a></li>
            <li><a href="../board?name=window-issues">Window Issues</a></li>
            <li><a href="../board?name=individual">개인</a></li>
            <li><a href="../develop_log">사이트 개발로그</a></li>
        </div>
        <!-- 위까지 공통 부분 -->
        <div class="body-content">
            <div class="wrap-content">
                <div class="content-field-wrapper">
                    <div class="content-box">
                        <div class="post-title-board">
                            <h2>{{ board_name }} 게시판</h2>
                        </div>
                        <hr style="width: 90%; height: 2px; border:none; background-color: black">
                        <div class="post-content-wrapper">
                            <div class="post-body-wrapper">
                                <div class="post-path-content">
                                    <div class="post-title">
                                        {{ doc_data.doc_title }}
                                    </div>
                                    <div class="post-poster">
                                        {{ doc_data.doc_writer }} | {{ doc_data.doc_time }}
                                    </div>
                                    <div class="post-view-cnt">
                                        조회수 : {{ doc_data.doc_view_cnt }}
                                    </div>
                                </div>
                                <div class="post-content">
                                    {{ doc_data.doc_content|safe }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="comment-box-wrapper">
                        <div class="comment-box-content">
                            <div class="comment-box-title">
                                <h2>댓글</h2>
                            </div>
                            <hr style="width: 90%; height: 2px; border:none; background-color: black">
                            <div class="show-comment-list">
                                {% if post.commented.all.count == 0 %}
                                {% else %}
                                    <div class="show-content-box-wrapper">
                                        <div class="comment-list-wrapper">
                                            {% for comment in post.commented.all %}
                                                <div class="single-comment-wrapper">
                                                    <div class="comment-writer">{{ comment.comment_writer.user_nickname }}</div>
                                                    <div class="comment-time">{{ comment.comment_time }}</div>
                                                    {% if request.session.userid == comment.comment_writer.user_id or request.session.userid == superuser_id %}
                                                        <div class="comment-delete">
                                                            <form action="comment/delete?comment_id={{ comment.comment_id }}" method="post" onsubmit="return saveScroll()">
                                                                {% csrf_token %}
                                                                <button id="button-like-a" type="submit">삭제</button>
                                                            </form>
                                                        </div>
                                                    {% endif %}
                                                    <hr style="width: 97%; height: 1px; border:none; background-color: grey">
                                                    <div class="comment-content">{{ comment.comment_content }}</div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="comment-write-wrapper">
                                <div class="write-comment-box">
                                    <div class="write-content-wrapper">
                                        <form action="{% url 'home:new_comment'%}" method="post" id="forms" onsubmit="return saveComment()">
                                            {% csrf_token %}
                                            <input type="hidden" name="post_id" value="{{ doc_data.doc_index }}"/>
                                            <div class="write-comment-content">
                                                <textarea name="comment_contents" placeholder="Leave a comment..." id="textarea-comment"></textarea>
                                            </div>
                                            <div class="save-comment">
                                                <button type="submit" id="comment_save_btn">등록</button>
                                            </div>
                                        </form>
                                        <script>
                                            function saveComment(){
                                                comment_content = document.getElementById('textarea-comment').value;
                                                if(comment_content.length == 0){
                                                    document.getElementById('textarea-comment').style.border="1px solid rgba(238, 23, 28, 1)";
                                                    document.getElementById('textarea-comment').style.boxShadow="0 0 5px rgba(238, 23, 28, 1)";
                                                    return false;
                                                }
                                                localStorage.setItem("scroll-position", $(window).scrollTop());
                                                return true;
                                            }
                                            function saveScroll() {
                                                localStorage.setItem("scroll-position", $(window).scrollTop());
                                                return true;
                                            }
                                        </script>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" id="refreshed" value="false">
                            <div class="navigator-wrapper">
{#                                <div class="prev-wrapper">#}
{#                                    {% if posts.has_previous %}#}
{#                                        <a href="?name={{ classification }}&page={{ posts.previous_page_number }}">prev</a>#}
{#                                    {% else %}#}
{#                                        <a style="color: #CCCCCC;">prev</a>#}
{#                                    {% endif %}#}
{#                                </div>#}
{#                                <div class="page-navigator">#}
{#                                    {% for page in posts.paginator.page_range %}#}
{#                                        {% if page in page_range %}#}
{#                                            <li class="page-linker">#}
{#                                                {% if posts.number == page %}#}
{#                                                    <strong style="color: #5555EE;">{{ page }}</strong>#}
{#                                                {% else %}#}
{#                                                    <a href="?name={{ classification }}&page={{ page }}">{{ page }}</a>#}
{#                                                {% endif %}#}
{#                                            </li>#}
{#                                        {% endif %}#}
{#                                    {% endfor %}#}
{#                                </div>#}
{#                                <div class="next-wrapper">#}
{#                                    {% if posts.has_next %}#}
{#                                        <a href="?name={{ classification }}&page={{ posts.next_page_number }}">next</a>#}
{#                                    {% else %}#}
{#                                        <a style="color: #CCCCCC;">next</a>#}
{#                                    {% endif %}#}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>